import type { Metadata } from 'next';
import './globals.css';
import '@/core/utils/dayjs';
import 'overlayscrollbars/overlayscrollbars.css';
import { Poppins } from 'next/font/google';
import RootProvider from '@/ui/boot/provider';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={poppins.className}>
      <RootProvider>{children}</RootProvider>
    </html>
  );
}
