import type { Metadata } from 'next';
import './globals.css';
import { Poppins } from 'next/font/google';
import Header from '@/ui/components/header';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={poppins.className}>
      <body className='dark'>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
